CREATE TABLE app_user
(
    username VARCHAR(50) NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (username)
);

INSERT INTO app_user (username)
VALUES ('user');

--
CREATE TABLE customer
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance     DECIMAL(19, 2),
    external_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_external UNIQUE (external_id);

--
CREATE TABLE transaction
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount        DECIMAL(19, 2)                          NOT NULL,
    timestamp     TIMESTAMP                               NOT NULL,
    load_id       BIGINT                                  NOT NULL,
    accepted      BOOLEAN                                 NOT NULL,
    user_username VARCHAR(50),
    customer_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

ALTER TABLE transaction
    ADD CONSTRAINT uc_transaction_load_id UNIQUE (load_id, customer_id);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_USER_USERNAME FOREIGN KEY (user_username) REFERENCES app_user (username);
